### ISSUE TITLE
Error on install: No such file or directory: './auto_completion.sh'

### ISSUE THREAD

**Issue by candlerb** [kaufland-ecommerce/esque#119]
Platform: Ubuntu 18.04 (in lxd container)

Doing "pip3 install esque" gives the following.

```
ubuntu@ldex-kafka:~$ sudo pip3 install esque
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting esque
  Downloading https://files.pythonhosted.org/packages/c6/b2/d66a60bea2c1edd330e5f16e6cd7d03828485a3217b9398b1cac11af24a6/esque-0.1.4a0.tar.gz
Collecting click>=7.0 (from esque)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 9.9MB/s
Requirement already satisfied: confluent-kafka in /usr/local/lib/python3.6/dist-packages (from esque)
Collecting pendulum (from esque)
  Downloading https://files.pythonhosted.org/packages/97/57/8c2b030119eb1badb74eb42e6dbccdd08bf79d76a057e758c0bd49959292/pendulum-2.0.5-cp36-cp36m-manylinux1_x86_64.whl (141kB)
    100% |████████████████████████████████| 143kB 7.2MB/s
Requirement already satisfied: pip>=9.0.1 in /usr/lib/python3/dist-packages (from esque)
Collecting pykafka (from esque)
  Downloading https://files.pythonhosted.org/packages/55/4b/4828ec5ed766cca0c27de234688122494c5762965e70deeb88b84f5d8d98/pykafka-2.8.0.tar.gz (141kB)
    100% |████████████████████████████████| 143kB 6.8MB/s
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from esque)
Requirement already satisfied: setuptools>=36.2.1 in /usr/lib/python3/dist-packages (from esque)
Collecting virtualenv (from esque)
  Downloading https://files.pythonhosted.org/packages/c5/97/00dd42a0fc41e9016b23f07ec7f657f636cb672fad9cf72b80f8f65c6a46/virtualenv-16.7.7-py2.py3-none-any.whl (3.4MB)
    100% |████████████████████████████████| 3.4MB 329kB/s
Collecting pytzdata>=2018.3 (from pendulum->esque)
  Downloading https://files.pythonhosted.org/packages/7f/f9/cdd39831b0465285c02ed90cfbf0db25bb951cb2a35ded0e69222375bea3/pytzdata-2019.3-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 2.9MB/s
Collecting python-dateutil<3.0,>=2.6 (from pendulum->esque)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 4.7MB/s
Collecting kazoo==2.5.0 (from pykafka->esque)
  Downloading https://files.pythonhosted.org/packages/76/af/942ec55feb58f8774e88fa6fd63433b53f4ab1b0b1397ff9355280162ec0/kazoo-2.5.0-py2.py3-none-any.whl (129kB)
    100% |████████████████████████████████| 133kB 4.7MB/s
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from pykafka->esque)
Collecting tabulate (from pykafka->esque)
  Downloading https://files.pythonhosted.org/packages/c4/41/523f6a05e6dc3329a5660f6a81254c6cd87e5cfb5b7482bae3391d86ec3a/tabulate-0.8.6.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 6.6MB/s
Installing collected packages: click, pytzdata, python-dateutil, pendulum, kazoo, tabulate, pykafka, virtualenv, esque
  Found existing installation: click 6.7
    Not uninstalling click at /usr/lib/python3/dist-packages, outside environment /usr
  Running setup.py install for tabulate ... done
  Running setup.py install for pykafka ... done
  Running setup.py install for esque ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-igj5s04t/esque/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7ynlu5f0-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '0.1.4a' to '0.1.4a0'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/esque
    copying esque/consumergroup.py -> build/lib/esque
    copying esque/__version__.py -> build/lib/esque
    copying esque/broker.py -> build/lib/esque
    copying esque/__main__.py -> build/lib/esque
    copying esque/topic.py -> build/lib/esque
    copying esque/config.py -> build/lib/esque
    copying esque/__init__.py -> build/lib/esque
    copying esque/helpers.py -> build/lib/esque
    copying esque/errors.py -> build/lib/esque
    copying esque/cluster.py -> build/lib/esque
    copying esque/clients.py -> build/lib/esque
    copying esque/environment.py -> build/lib/esque
    creating build/lib/config
    copying config/__init__.py -> build/lib/config
    creating build/lib/esque/cli
    copying esque/cli/output.py -> build/lib/esque/cli
    copying esque/cli/commands.py -> build/lib/esque/cli
    copying esque/cli/options.py -> build/lib/esque/cli
    copying esque/cli/__init__.py -> build/lib/esque/cli
    copying esque/cli/helpers.py -> build/lib/esque/cli
    running egg_info
    writing esque.egg-info/PKG-INFO
    writing dependency_links to esque.egg-info/dependency_links.txt
    writing entry points to esque.egg-info/entry_points.txt
    writing requirements to esque.egg-info/requires.txt
    writing top-level names to esque.egg-info/top_level.txt
    reading manifest file 'esque.egg-info/SOURCES.txt'
    writing manifest file 'esque.egg-info/SOURCES.txt'
    running install_lib
    creating /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/consumergroup.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/__version__.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/broker.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/__main__.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/topic.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/config.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/__init__.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/helpers.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/errors.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/cluster.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/clients.py -> /usr/local/lib/python3.6/dist-packages/esque
    copying build/lib/esque/environment.py -> /usr/local/lib/python3.6/dist-packages/esque
    creating /usr/local/lib/python3.6/dist-packages/esque/cli
    copying build/lib/esque/cli/output.py -> /usr/local/lib/python3.6/dist-packages/esque/cli
    copying build/lib/esque/cli/commands.py -> /usr/local/lib/python3.6/dist-packages/esque/cli
    copying build/lib/esque/cli/options.py -> /usr/local/lib/python3.6/dist-packages/esque/cli
    copying build/lib/esque/cli/__init__.py -> /usr/local/lib/python3.6/dist-packages/esque/cli
    copying build/lib/esque/cli/helpers.py -> /usr/local/lib/python3.6/dist-packages/esque/cli
    creating /usr/local/lib/python3.6/dist-packages/config
    copying build/lib/config/__init__.py -> /usr/local/lib/python3.6/dist-packages/config
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/consumergroup.py to consumergroup.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/__version__.py to __version__.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/broker.py to broker.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/__main__.py to __main__.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/topic.py to topic.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/config.py to config.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/__init__.py to __init__.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/helpers.py to helpers.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/errors.py to errors.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/cluster.py to cluster.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/clients.py to clients.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/environment.py to environment.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/cli/output.py to output.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/cli/commands.py to commands.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/cli/options.py to options.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/cli/__init__.py to __init__.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/esque/cli/helpers.py to helpers.cpython-36.pyc
    byte-compiling /usr/local/lib/python3.6/dist-packages/config/__init__.py to __init__.cpython-36.pyc
    running install_egg_info
    Copying esque.egg-info to /usr/local/lib/python3.6/dist-packages/esque-0.1.4a0.egg-info
    running install_scripts
    Installing esque script to /usr/local/bin
    writing list of installed files to '/tmp/pip-7ynlu5f0-record/install-record.txt'
    installing auto completion
    error: [Errno 2] No such file or directory: './auto_completion.sh': './auto_completion.sh'

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-igj5s04t/esque/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7ynlu5f0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-igj5s04t/esque/
ubuntu@ldex-kafka:~$
```

If I repeat the command (this time with `-H` as it suggests), it thinks it's installed.

```
ubuntu@ldex-kafka:~$ sudo -H pip3 install esque
Requirement already satisfied: esque in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.6/dist-packages (from esque)
Requirement already satisfied: confluent-kafka in /usr/local/lib/python3.6/dist-packages (from esque)
Requirement already satisfied: pendulum in /usr/local/lib/python3.6/dist-packages (from esque)
Requirement already satisfied: pip>=9.0.1 in /usr/lib/python3/dist-packages (from esque)
Requirement already satisfied: pykafka in /usr/local/lib/python3.6/dist-packages (from esque)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from esque)
Requirement already satisfied: setuptools>=36.2.1 in /usr/lib/python3/dist-packages (from esque)
Requirement already satisfied: virtualenv in /usr/local/lib/python3.6/dist-packages (from esque)
Requirement already satisfied: pytzdata>=2018.3 in /usr/local/lib/python3.6/dist-packages (from pendulum->esque)
Requirement already satisfied: python-dateutil<3.0,>=2.6 in /usr/local/lib/python3.6/dist-packages (from pendulum->esque)
Requirement already satisfied: kazoo==2.5.0 in /usr/local/lib/python3.6/dist-packages (from pykafka->esque)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from pykafka->esque)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from pykafka->esque)
ubuntu@ldex-kafka:~$
```

But it appears to be missing parts (`sample_config.cfg`)

```
ubuntu@ldex-kafka:~$ esque describe consumergroup
No config provided in /home/ubuntu/.esque
Should a sample file be created in /home/ubuntu/.esque [y/N]: y
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/esque/cli/options.py", line 19, in __init__
    self.config = Config()
  File "/usr/local/lib/python3.6/dist-packages/esque/config.py", line 41, in __init__
    raise ConfigNotExistsException("No config defined.")
esque.errors.ConfigNotExistsException: No config defined.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/esque", line 11, in <module>
    load_entry_point('esque==0.1.4a0', 'console_scripts', 'esque')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 57, in new_func
    obj = ctx.ensure_object(object_type)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 477, in ensure_object
    self.obj = rv = object_type()
  File "/usr/local/lib/python3.6/dist-packages/esque/cli/options.py", line 24, in __init__
    copyfile(sample_config_path().as_posix(), config_path())
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/config/sample_config.cfg'
ubuntu@ldex-kafka:~$
```

**Comment by candlerb** [comment]
Maybe related to #94 / #95.

pip3 says I have `esque (0.1.4a0)`.  I presume that's from tag v0.1.4a (Jul 11 2019).  Maybe a new package needs pushing out?

I updated pip3 using `sudo -H pip3 install --upgrade pip`, then tried uninstalling and reinstalling resque, but got the same error.

Then tried to install from git:

```
ubuntu@ldex-kafka:~$ sudo -H pip3 install git+https://github.com/real-digital/esque.git@370c8cf373d8f905bb22764b906f6a44f51759e6
Collecting git+https://github.com/real-digital/esque.git@370c8cf373d8f905bb22764b906f6a44f51759e6
  Cloning https://github.com/real-digital/esque.git (to revision 370c8cf373d8f905bb22764b906f6a44f51759e6) to /tmp/pip-req-build-r7jmz5n1
  Running command git clone -q https://github.com/real-digital/esque.git /tmp/pip-req-build-r7jmz5n1
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting fastavro<0.23.0,>=0.22.5
  Using cached https://files.pythonhosted.org/packages/06/b4/7b11afb5d6684de07ddff2e45dbf7338b847ffdfe67035ae257c83c40f4d/fastavro-0.22.7-cp36-cp36m-manylinux1_x86_64.whl
Collecting requests<3.0,>=2.22
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Requirement already satisfied: confluent-kafka[avro]<2.0,>=1.2 in /usr/local/lib/python3.6/dist-packages (from esque==0.2.0a0) (1.2.0)
Requirement already satisfied: pendulum<3.0,>=2.0 in /usr/local/lib/python3.6/dist-packages (from esque==0.2.0a0) (2.0.5)
Requirement already satisfied: pykafka@ git+https://github.com/real-digital/pykafka.git@feature/sasl-scram-support from git+https://github.com/real-digital/pykafka.git@feature/sasl-scram-support in /usr/local/lib/python3.6/dist-packages (from esque==0.2.0a0) (2.8.0)
Requirement already satisfied: click<8.0,>=7.0 in /usr/local/lib/python3.6/dist-packages (from esque==0.2.0a0) (7.0)
Collecting pyyaml<6.0,>=5.1
  Using cached https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz
Collecting toml<0.11.0,>=0.10.0
  Using cached https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting avro-python3==1.8.2
  Using cached https://files.pythonhosted.org/packages/63/b4/7a81640bb69c844c912987007ba36276c29690d6fde2cd41fec16cd24c3b/avro-python3-1.8.2.tar.gz
Collecting yamale<3.0,>=2.0
  Using cached https://files.pythonhosted.org/packages/c9/dd/6f559c5738f5e6616393e2163aa3c538bdec8b7f3755af12182a032727f2/yamale-2.0.1.tar.gz
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0,>=2.22->esque==0.2.0a0) (2.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<3.0,>=2.22->esque==0.2.0a0) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests<3.0,>=2.22->esque==0.2.0a0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0,>=2.22->esque==0.2.0a0) (2018.1.18)
Requirement already satisfied: pytzdata>=2018.3 in /usr/local/lib/python3.6/dist-packages (from pendulum<3.0,>=2.0->esque==0.2.0a0) (2019.3)
Requirement already satisfied: python-dateutil<3.0,>=2.6 in /usr/local/lib/python3.6/dist-packages (from pendulum<3.0,>=2.0->esque==0.2.0a0) (2.8.1)
Requirement already satisfied: kazoo==2.5.0 in /usr/local/lib/python3.6/dist-packages (from pykafka@ git+https://github.com/real-digital/pykafka.git@feature/sasl-scram-support->esque==0.2.0a0) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from pykafka@ git+https://github.com/real-digital/pykafka.git@feature/sasl-scram-support->esque==0.2.0a0) (1.11.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from pykafka@ git+https://github.com/real-digital/pykafka.git@feature/sasl-scram-support->esque==0.2.0a0) (0.8.6)
Building wheels for collected packages: esque
  Building wheel for esque (PEP 517) ... done
  Created wheel for esque: filename=esque-0.2.0a0-cp36-none-any.whl size=61074 sha256=0a6059347dd7076babcfe7c2bb519ba919bc0aefa3fd88763c80f4c2ba5e9ffb
  Stored in directory: /tmp/pip-ephem-wheel-cache-acz8bbhx/wheels/10/bd/cd/6b4134d30b2ba7394f0d5b2d055c006adc53bb4a5e822c4079
Successfully built esque
Installing collected packages: fastavro, requests, pyyaml, toml, avro-python3, yamale, esque
  Found existing installation: requests 2.18.4
    Uninstalling requests-2.18.4:
      Successfully uninstalled requests-2.18.4
  Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

It appears unhappy that I have the system `python3-yaml` apt package installed `:-(`

**Comment by hfjn** [comment]
Hi @candlerb thanks for wanting to try out `esque` :). Yeah we had a few issues in the alpha release pushed to pypi some time ago. Since we were only using the tool internally so far pushing out a new release had very low priority. **But**(!) we are currently working on pushing out a new working beta release which should be available any day now. For now you could try to install `esque` by using [poetry](https://github.com/sdispater/poetry).

Just clone the repo and run `poetry install` from within the repo folder.
`poetry run esque` will then allow you to start using `esque` in "development" mode.

**Comment by hfjn** [comment]
Just released a new version. ```pip3 install --user esque``` should now work for you. :)

**Comment by candlerb** [comment]
Thank you!

FYI, the PyYAML error comes from [pip >= 10](https://github.com/pypa/pip/issues/5247), so I downgraded pip to 9.0.3.  It's happy now.

**Comment by hfjn** [comment]
That's weird. Thanks for the heads up!
