### ISSUE TITLE
MessageEmptyException for most commands

### ISSUE THREAD

**Issue by Bibob7** [kaufland-ecommerce/esque#125]
For several commands, I tested, I see a `MessageEmptyException`.

For example for `esque describe topic shop-product_export_best_unit --verbose` I see:

```
Traceback (most recent call last):
  File "/Users/kevin/Library/Python/3.7/bin/esque", line 10, in <module>
    sys.exit(esque())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/cli/options.py", line 120, in wrapper
    f(*args, **kwargs)
  File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/cli/commands.py", line 477, in describe_topic
    topic = state.cluster.topic_controller.get_cluster_topic(topic_name)
  File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/controller/topic_controller.py", line 108, in get_cluster_topic
    return self.update_from_cluster(Topic(topic_name))
  File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/controller/topic_controller.py", line 162, in update_from_cluster
    topic.partition_data = self._get_partition_data(confluent_topic, low_watermarks, high_watermarks, topic)
  File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/controller/topic_controller.py", line 184, in _get_partition_data
    latest_timestamp = float(consumer.consume(high - 1, partition_id).timestamp()[1]) / 1000
  File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/clients/consumer.py", line 124, in consume
    return self.consume_single_message(timeout=1)
  File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/clients/consumer.py", line 98, in consume_single_message
    raise_for_message(message)
  File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/errors.py", line 19, in raise_for_message
    raise MessageEmptyException
esque.errors.MessageEmptyException
```

**Comment by swenzel** [comment]
>   File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/clients/consumer.py", line 124, in consume
>     return self.consume_single_message(timeout=1)

That timeout is a little too short, if you ask me ^^
Still, I think we should catch the exception here:

> File "/Users/kevin/Library/Python/3.7/lib/python/site-packages/esque/controller/topic_controller.py", line 184, in _get_partition_data
>     latest_timestamp = float(consumer.consume(high - 1, partition_id).timestamp()[1]) / 1000

Just in case. Maybe warn the user via stderr, that due to timeout the latest timestamp is missing.

**Comment by Bibob7** [comment]
I found this:

```
    def consume_single_acceptable_message(self, timeout=30) -> Optional[Message]:
        message_acceptable = False
        total_time_remaining = timeout
        message = None
        while not message_acceptable and total_time_remaining > 0:
            iteration_start = pendulum.now()
            message = self.consume_single_message(timeout=timeout)
            total_time_remaining -= (pendulum.now() - iteration_start).in_seconds()
            message_acceptable = self.consumed_message_matches(message)
        return message if message_acceptable else None
```

What is the idea of that?

**Comment by swenzel** [comment]
You can use that to consume a message that satisfies a filter.

**Comment by swenzel** [comment]
Closed by https://github.com/real-digital/esque/pull/126
