### ISSUE TITLE
Config initialization doesn't properly work.

### ISSUE THREAD

**Issue by hfjn** [kaufland-ecommerce/esque#2]
The sample_config is not part of the released package.

```Traceback (most recent call last):
  File "/Users/hfjn/.pyenv/versions/3.6.7/bin/esque", line 11, in <module>
    load_entry_point('esque==0.1.0', 'console_scripts', 'esque')()
  File "/Users/hfjn/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hfjn/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/hfjn/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hfjn/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hfjn/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hfjn/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/hfjn/.local/lib/python3.6/site-packages/click/decorators.py", line 57, in new_func
    obj = ctx.ensure_object(object_type)
  File "/Users/hfjn/.local/lib/python3.6/site-packages/click/core.py", line 477, in ensure_object
    self.obj = rv = object_type()
  File "/Users/hfjn/.pyenv/versions/3.6.7/lib/python3.6/site-packages/esque/cli/options.py", line 27, in __init__
    config_path(),
  File "/Users/hfjn/.pyenv/versions/3.6.7/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hfjn/.pyenv/versions/3.6.7/lib/python3.6/site-packages/sample_config.cfg'```

**Comment by hfjn** [comment]
Still doesn't work.
